// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdOVJGwr7_hJf71K5fqVRulfgfvrwCXnc',
    appId: '1:196717629896:web:8f88617ea94e5cea0af0fd',
    messagingSenderId: '196717629896',
    projectId: 'ngumpulin-b0edd',
    authDomain: 'ngumpulin-b0edd.firebaseapp.com',
    storageBucket: 'ngumpulin-b0edd.firebasestorage.app',
    measurementId: 'G-FV25XTHCM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL5kHqor7KSVkU8QUNbtg556jhLg3GXqA',
    appId: '1:196717629896:android:796b2cbfcdee1ef80af0fd',
    messagingSenderId: '196717629896',
    projectId: 'ngumpulin-b0edd',
    storageBucket: 'ngumpulin-b0edd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3fkF9xnYeK4CfjLJsO3W6_3Fio8KN0oU',
    appId: '1:196717629896:ios:875df46d3e0532fd0af0fd',
    messagingSenderId: '196717629896',
    projectId: 'ngumpulin-b0edd',
    storageBucket: 'ngumpulin-b0edd.firebasestorage.app',
    iosBundleId: 'com.ngumpulin.ngumpulIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3fkF9xnYeK4CfjLJsO3W6_3Fio8KN0oU',
    appId: '1:196717629896:ios:875df46d3e0532fd0af0fd',
    messagingSenderId: '196717629896',
    projectId: 'ngumpulin-b0edd',
    storageBucket: 'ngumpulin-b0edd.firebasestorage.app',
    iosBundleId: 'com.ngumpulin.ngumpulIn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdOVJGwr7_hJf71K5fqVRulfgfvrwCXnc',
    appId: '1:196717629896:web:6ee059808d4da1db0af0fd',
    messagingSenderId: '196717629896',
    projectId: 'ngumpulin-b0edd',
    authDomain: 'ngumpulin-b0edd.firebaseapp.com',
    storageBucket: 'ngumpulin-b0edd.firebasestorage.app',
    measurementId: 'G-N3X808J28Q',
  );
}
